### ISSUE TITLE
Remove telemetry

### ISSUE THREAD

**Issue by jaydenseric** [davidreis97/Crashacters#11]
Thanks for disclosing in the readme that this extension has Microsoft Azure Application Insights telemetry, but can you please remove it? A lot of people (myself included) are not keen on installing an extension that phones home. I can't see why it's justified for such a focused extension. If you want to test performance for some reason, write tests that measure processing time for various lengths of files.

**Comment by davidreis97** [comment]
Hi @jaydenseric,

Telemetry was helpful in the first few weeks to check that no errors were being thrown and that performance was good even in computers that were not as performant as mine or that had different architectures and OSs. However, given that since launch I've seen no issues, I feel comfortable in completely removing the telemetry now.
